metric: COCO
num_classes: 9

TrainDataset:
  name: COCODataSet
  image_dir: images_s/train
  anno_path: instances_train.json
  dataset_dir: /home/ubuntu/weld-training-fs/multiscale-final-coco-640s
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images_s/val
  anno_path: instances_val.json
  dataset_dir: /home/ubuntu/weld-training-fs/multiscale-final-coco-640s
  allow_empty: true

TestDataset:
  name: COCODataSet
  image_dir: images_s/val
  anno_path: instances_val.json
  dataset_dir: /home/ubuntu/weld-training-fs/multiscale-final-coco-640s
  allow_empty: true